/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CounselorBooking = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
});
export const College = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'hasResearchOpportunities' : IDL.Bool,
  'areasOfInterest' : IDL.Vec(IDL.Text),
  'ranking' : IDL.Nat,
});
export const LearningOpportunity = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'category' : IDL.Variant({ 'internal' : IDL.Null, 'external' : IDL.Null }),
  'organization' : IDL.Text,
});
export const Resource = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'resourceType' : IDL.Variant({
    'example' : IDL.Null,
    'guide' : IDL.Null,
    'template' : IDL.Null,
  }),
  'fileUrl' : IDL.Text,
});
export const Scholarship = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'scholarshipType' : IDL.Variant({
    'merit' : IDL.Null,
    'subject' : IDL.Null,
    'need' : IDL.Null,
  }),
  'fieldOfStudy' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'academicAchievements' : IDL.Vec(IDL.Text),
  'extracurricularActivities' : IDL.Vec(IDL.Text),
  'awards' : IDL.Vec(IDL.Text),
  'leadershipRoles' : IDL.Vec(IDL.Text),
  'internships' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(CounselorBooking)], ['query']),
  'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getAllOpportunities' : IDL.Func(
      [],
      [IDL.Vec(LearningOpportunity)],
      ['query'],
    ),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpportunitiesByCategory' : IDL.Func(
      [IDL.Variant({ 'internal' : IDL.Null, 'external' : IDL.Null })],
      [IDL.Vec(LearningOpportunity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func([CounselorBooking], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CounselorBooking = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
  });
  const College = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'hasResearchOpportunities' : IDL.Bool,
    'areasOfInterest' : IDL.Vec(IDL.Text),
    'ranking' : IDL.Nat,
  });
  const LearningOpportunity = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'category' : IDL.Variant({ 'internal' : IDL.Null, 'external' : IDL.Null }),
    'organization' : IDL.Text,
  });
  const Resource = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'resourceType' : IDL.Variant({
      'example' : IDL.Null,
      'guide' : IDL.Null,
      'template' : IDL.Null,
    }),
    'fileUrl' : IDL.Text,
  });
  const Scholarship = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'scholarshipType' : IDL.Variant({
      'merit' : IDL.Null,
      'subject' : IDL.Null,
      'need' : IDL.Null,
    }),
    'fieldOfStudy' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'academicAchievements' : IDL.Vec(IDL.Text),
    'extracurricularActivities' : IDL.Vec(IDL.Text),
    'awards' : IDL.Vec(IDL.Text),
    'leadershipRoles' : IDL.Vec(IDL.Text),
    'internships' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(CounselorBooking)], ['query']),
    'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getAllOpportunities' : IDL.Func(
        [],
        [IDL.Vec(LearningOpportunity)],
        ['query'],
      ),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpportunitiesByCategory' : IDL.Func(
        [IDL.Variant({ 'internal' : IDL.Null, 'external' : IDL.Null })],
        [IDL.Vec(LearningOpportunity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func([CounselorBooking], [], []),
  });
};

export const init = ({ IDL }) => { return []; };